version: '3.7'
services:
  service_encrypt:
    build: ./encryptjson

  service_decrypt:
    build: ./xmldecrypt
    volumes:
      - /var/lib/docker/volumes/jsontoxmlvolume/_data:/home/encryptedxml
      - /var/lib/docker/volumes/jsontoxmlvolume/_data:/home/secret
  